services:
  - type: web
    name: audit-assistant
    env: python
    buildCommand: |
      pip install -e .
    startCommand: gunicorn --worker-tmp-dir /dev/shm --timeout 120 --bind 0.0.0.0:10000 wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: audit_assistant.app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: 3a359880a6ca37316e5e9565d7f731f89e676a0c3956a286
    plan: free
